package com.cptbendova.rolecraftvault;

import android.content.SharedPreferences;
import android.content.Context;
import android.net.wifi.WifiManager;
import android.security.keystore.KeyGenParameterSpec;
import android.security.keystore.KeyProperties;
import android.util.Base64;
import com.getcapacitor.*;
import com.getcapacitor.annotation.CapacitorPlugin;
import org.json.*;
import java.io.*;
import java.net.*;
import java.nio.charset.StandardCharsets;
import java.nio.file.*;
import java.security.*;
import java.util.*;
import java.util.concurrent.*;
import java.util.zip.*;
import javax.crypto.*;
import javax.crypto.spec.*;

/** Paired LAN-only immutable chunk transport. Never reads or writes vault records. */
@CapacitorPlugin(name="VaultSync")
public class VaultSyncPlugin extends Plugin {
    private static final String ALIAS="rolecraft-vault-sync-v1";
    private static final int DISCOVERY=44218,MAX=2*1024*1024,CHUNK=256*1024;
    private final ExecutorService worker=Executors.newSingleThreadExecutor(), servers=Executors.newFixedThreadPool(6);
    private final Map<String,JSONObject> peers=new ConcurrentHashMap<>();
    private final Map<String,Long> nonces=new ConcurrentHashMap<>();
    private final Set<Socket> sockets=ConcurrentHashMap.newKeySet();
    private final Set<String> retained=new HashSet<>();
    private volatile JSONObject cfg;
    private volatile ServerSocket server;
    private volatile DatagramSocket udp;
    private WifiManager.MulticastLock discoveryLock;
    private volatile HttpURLConnection outgoing;
    private volatile long lease=0;
    private volatile int epoch=0,port=0;
    private volatile String ip;
    private static byte[] bytes(String s){return s.getBytes(StandardCharsets.UTF_8);}
    private static String hex(byte[] data){StringBuilder s=new StringBuilder();for(byte b:data)s.append(String.format(Locale.ROOT,"%02x",b&255));return s.toString();}
    private static byte[] unhex(String s){byte[] b=new byte[s.length()/2];for(int i=0;i<b.length;i++)b[i]=(byte)Integer.parseInt(s.substring(i*2,i*2+2),16);return b;}
    private static String digest(String s)throws Exception{return hex(MessageDigest.getInstance("SHA-256").digest(bytes(s)));}
    private static String random(int n){byte[] b=new byte[n];new SecureRandom().nextBytes(b);return hex(b);}
    private static boolean privateIp(String ip){if(ip==null||!ip.matches("[0-9]{1,3}(\\.[0-9]{1,3}){3}"))return false;String[] p=ip.split("\\.");for(String n:p)if(Integer.parseInt(n)>255)return false;int a=Integer.parseInt(p[0]),b=Integer.parseInt(p[1]);return a==10||a==192&&b==168||a==172&&b>=16&&b<=31;}
    private static List<String> addresses()throws Exception{List<String> out=new ArrayList<>();Enumeration<NetworkInterface> nets=NetworkInterface.getNetworkInterfaces();while(nets.hasMoreElements()){NetworkInterface net=nets.nextElement();if(!net.isUp()||net.isLoopback()||net.isPointToPoint())continue;for(InterfaceAddress a:net.getInterfaceAddresses()){String ip=a.getAddress().getHostAddress();if(privateIp(ip)){if(net.getName().startsWith("wlan")||net.getName().startsWith("eth"))out.add(0,ip);else out.add(ip);}}}return out;}
    private File directory(){return new File(getContext().getFilesDir(),"vault-sync");}
    private File head(){return new File(directory(),"head.bin");}
    private File chunk(String hash)throws Exception{if(!hash.matches("[a-f0-9]{64}"))throw new IOException("Invalid chunk identity");return new File(new File(directory(),"chunks"),hash);}
    private SharedPreferences prefs(){return getContext().getSharedPreferences(ALIAS,0);}
    private SecretKey storageKey()throws Exception{KeyStore s=KeyStore.getInstance("AndroidKeyStore");s.load(null);if(s.containsAlias(ALIAS))return(SecretKey)s.getKey(ALIAS,null);KeyGenerator g=KeyGenerator.getInstance(KeyProperties.KEY_ALGORITHM_AES,"AndroidKeyStore");g.init(new KeyGenParameterSpec.Builder(ALIAS,KeyProperties.PURPOSE_ENCRYPT|KeyProperties.PURPOSE_DECRYPT).setBlockModes(KeyProperties.BLOCK_MODE_GCM).setEncryptionPaddings(KeyProperties.ENCRYPTION_PADDING_NONE).build());return g.generateKey();}
    private JSONObject loadConfig()throws Exception{if(cfg==null&&prefs().contains("sealed")){Cipher c=Cipher.getInstance("AES/GCM/NoPadding");c.init(Cipher.DECRYPT_MODE,storageKey(),new GCMParameterSpec(128,Base64.decode(prefs().getString("iv",""),Base64.NO_WRAP)));cfg=new JSONObject(new String(c.doFinal(Base64.decode(prefs().getString("sealed",""),Base64.NO_WRAP)),StandardCharsets.UTF_8));}if(cfg!=null&&(!cfg.optString("key").matches("[a-f0-9]{64}")||!cfg.optString("device").matches("[a-f0-9-]{36}")))throw new IOException("Pairing is damaged. Leave the group and pair again.");return cfg;}
    private void save(JSONObject value)throws Exception{Cipher c=Cipher.getInstance("AES/GCM/NoPadding");c.init(Cipher.ENCRYPT_MODE,storageKey());if(!prefs().edit().putString("iv",Base64.encodeToString(c.getIV(),Base64.NO_WRAP)).putString("sealed",Base64.encodeToString(c.doFinal(bytes(value.toString())),Base64.NO_WRAP)).commit())throw new IOException("Could not remember pairing");cfg=value;}
    private static void atomic(File f,String value)throws Exception{File parent=f.getParentFile();if(!parent.exists()&&!parent.mkdirs())throw new IOException("Sync cache storage is unavailable");File temp=new File(parent,f.getName()+".tmp-"+UUID.randomUUID());try{try(FileOutputStream out=new FileOutputStream(temp)){out.write(bytes(value));out.getFD().sync();}Files.move(temp.toPath(),f.toPath(),StandardCopyOption.REPLACE_EXISTING,StandardCopyOption.ATOMIC_MOVE);}finally{if(temp.exists())temp.delete();}}
    private static byte[] read(InputStream in,int limit)throws Exception{try(InputStream input=in;ByteArrayOutputStream out=new ByteArrayOutputStream()){byte[] b=new byte[32768];int n,total=0;while((n=input.read(b))!=-1){total+=n;if(total>limit)throw new IOException("Sync packet too large");out.write(b,0,n);}return out.toByteArray();}}
    private static String file(File f)throws Exception{return new String(read(new FileInputStream(f),MAX),StandardCharsets.UTF_8);}
    private static String seal(String text,String key,String aad)throws Exception{byte[] iv=unhex(random(12));ByteArrayOutputStream zipped=new ByteArrayOutputStream();try(GZIPOutputStream z=new GZIPOutputStream(zipped)){z.write(bytes(text));}Cipher c=Cipher.getInstance("AES/GCM/NoPadding");c.init(Cipher.ENCRYPT_MODE,new SecretKeySpec(unhex(key),"AES"),new GCMParameterSpec(128,iv));c.updateAAD(bytes("RCVSYNC1:"+aad));ByteArrayOutputStream out=new ByteArrayOutputStream();out.write(iv);out.write(c.doFinal(zipped.toByteArray()));return Base64.encodeToString(out.toByteArray(),Base64.NO_WRAP);}
    private static String unseal(String text,String key,String aad)throws Exception{if(text.length()>MAX||!text.matches("[A-Za-z0-9+/=]+"))throw new IOException("Invalid sync packet");byte[] b=Base64.decode(text,Base64.NO_WRAP);if(b.length<29)throw new IOException("Invalid sync packet");Cipher c=Cipher.getInstance("AES/GCM/NoPadding");c.init(Cipher.DECRYPT_MODE,new SecretKeySpec(unhex(key),"AES"),new GCMParameterSpec(128,Arrays.copyOf(b,12)));c.updateAAD(bytes("RCVSYNC1:"+aad));return new String(read(new GZIPInputStream(new ByteArrayInputStream(c.doFinal(b,12,b.length-12))),MAX),StandardCharsets.UTF_8);}
    private static String mac(String key,String value)throws Exception{Mac m=Mac.getInstance("HmacSHA256");m.init(new SecretKeySpec(unhex(key),"HmacSHA256"));return hex(m.doFinal(bytes(value)));}
    private boolean active(){return cfg!=null&&System.currentTimeMillis()<lease;}
    private void check(int run)throws Exception{if(run!=epoch||!active())throw new IOException("Sync paused. Open and unlock Rolecraft to resume.");}
    private void pauseWork(){epoch++;lease=0;try{if(server!=null)server.close();}catch(Exception ignored){}if(udp!=null)udp.close();if(discoveryLock!=null){if(discoveryLock.isHeld())discoveryLock.release();discoveryLock=null;}if(outgoing!=null)outgoing.disconnect();for(Socket s:sockets)try{s.close();}catch(Exception ignored){}sockets.clear();server=null;udp=null;port=0;ip=null;peers.clear();nonces.clear();}
    @Override protected void handleOnPause(){pauseWork();}
    @Override protected void handleOnDestroy(){pauseWork();worker.shutdownNow();servers.shutdownNow();}
    private JSONObject info()throws Exception{JSONObject r=new JSONObject();r.put("enabled",cfg!=null);if(cfg!=null){for(String k:new String[]{"device","primary","label","namespace"})r.put(k,cfg.optString(k));r.put("group",digest(cfg.getString("key")).substring(0,24));}return r;}
    private void remember(JSONObject p)throws Exception{if(cfg==null||p.optString("id").equals(cfg.optString("device"))||!p.optString("id").matches("[a-f0-9-]{36}")||!privateIp(p.optString("ip"))||p.optInt("port")<1024||p.optInt("port")>65535)return;JSONObject item=new JSONObject(p.toString());item.put("seen",System.currentTimeMillis());peers.put(item.getString("id"),item);if(peers.size()>32)peers.remove(peers.keySet().iterator().next());}
    private String signedPacket(String type,String nonce)throws Exception{String body=type+"|"+digest(cfg.getString("key")).substring(0,24)+"|"+cfg.getString("device")+"|"+nonce+"|"+System.currentTimeMillis()+"|"+port;return body+"|"+mac(cfg.getString("key"),body);}
    private void discoveryLoop(DatagramSocket socket,int run){while(run==epoch&&!socket.isClosed()){try{DatagramPacket p=new DatagramPacket(new byte[512],512);socket.receive(p);if(!active()||!privateIp(p.getAddress().getHostAddress()))continue;String[] a=new String(p.getData(),0,p.getLength(),StandardCharsets.UTF_8).split("\\|");if(a.length!=7||!a[1].equals(digest(cfg.getString("key")).substring(0,24))||Math.abs(System.currentTimeMillis()-Long.parseLong(a[4]))>120000)continue;String body=String.join("|",Arrays.copyOf(a,6));if(!MessageDigest.isEqual(bytes(a[6]),bytes(mac(cfg.getString("key"),body))))continue;remember(new JSONObject().put("id",a[2]).put("ip",p.getAddress().getHostAddress()).put("port",Integer.parseInt(a[5])));if(a[0].equals("RCVSYNC1?")){byte[] reply=bytes(signedPacket("RCVSYNC1!",a[3]));socket.send(new DatagramPacket(reply,reply.length,p.getAddress(),p.getPort()));}}catch(Exception ignored){}}}
    private static String line(InputStream in)throws Exception{ByteArrayOutputStream b=new ByteArrayOutputStream();int n;while((n=in.read())!=-1){if(n==10)break;if(n!=13)b.write(n);if(b.size()>4096)throw new IOException("Invalid HTTP header");}return b.toString("US-ASCII");}
    private void serve(Socket socket,int run){try(Socket s=socket){sockets.add(s);s.setSoTimeout(12000);InputStream in=new BufferedInputStream(s.getInputStream());OutputStream out=s.getOutputStream();String first=line(in);int length=-1,total=0;for(String h;(h=line(in)).length()>0;){total+=h.length();if(total>8192)throw new IOException("Headers too large");if(h.toLowerCase(Locale.ROOT).startsWith("content-length:"))length=Integer.parseInt(h.substring(15).trim());if(h.toLowerCase(Locale.ROOT).startsWith("transfer-encoding:"))throw new IOException("Chunked HTTP not supported");}check(run);if(!privateIp(s.getInetAddress().getHostAddress())||!first.equals("POST /sync HTTP/1.1")||length<1||length>MAX)throw new IOException("Invalid sync request");byte[] body=new byte[length];new DataInputStream(in).readFully(body);JSONObject request=new JSONObject(unseal(new String(body,StandardCharsets.UTF_8),cfg.getString("key"),"request"));remember(new JSONObject().put("id",request.optString("device")).put("ip",s.getInetAddress().getHostAddress()).put("port",request.optInt("port")));String nonce=request.optString("nonce");long now=System.currentTimeMillis();if(!nonce.matches("[a-f0-9]{32}")||Math.abs(now-request.optLong("at"))>120000||nonces.putIfAbsent(nonce,now)!=null)throw new IOException("Expired request");for(Map.Entry<String,Long> e:nonces.entrySet())if(now-e.getValue()>120000)nonces.remove(e.getKey());if(nonces.size()>4096)throw new IOException("Too many requests");JSONObject result=new JSONObject();if(request.optString("action").equals("index")){result.put("head",head().exists()?new JSONObject(unseal(file(head()),cfg.getString("key"),"head")):JSONObject.NULL);result.put("device",cfg.getString("device"));result.put("label",cfg.optString("label"));result.put("peers",new JSONArray(peers.values()));}else if(request.optString("action").equals("chunk")){String hash=request.getString("hash");File f=chunk(hash);String packet=file(f);try{if(!digest(unseal(packet,cfg.getString("key"),"blob:"+hash)).equals(hash))throw new IOException("Checksum failed");}catch(Exception damaged){f.delete();throw new IOException("Cached chunk damaged; rebuilding from the vault");}result.put("packet",packet);}else throw new IOException("Unknown sync action");check(run);byte[] reply=bytes(seal(new JSONObject().put("nonce",nonce).put("result",result).toString(),cfg.getString("key"),"response"));out.write(bytes("HTTP/1.1 200 OK\r\nContent-Type: text/plain\r\nConnection: close\r\nCache-Control: no-store\r\nContent-Length: "+reply.length+"\r\n\r\n"));out.write(reply);out.flush();}catch(Exception ignored){}finally{sockets.remove(socket);}}
    private void resume(int run)throws Exception{if(loadConfig()==null)throw new IOException("Choose or join a sync group first");if(run!=epoch)throw new IOException("Sync paused");List<String> local=addresses();if(local.isEmpty())throw new IOException("Waiting for a private local network");lease=System.currentTimeMillis()+20000;if(server!=null&&local.get(0).equals(ip))return;if(server!=null)throw new IOException("Network changed. Sync will reconnect.");ip=local.get(0);ServerSocket s=new ServerSocket();s.setReuseAddress(true);s.bind(new InetSocketAddress(InetAddress.getByName(ip),0),8);server=s;port=s.getLocalPort();servers.execute(()->{while(run==epoch&&!s.isClosed())try{Socket accepted=s.accept();if(sockets.size()>=8){accepted.close();continue;}sockets.add(accepted);servers.execute(()->serve(accepted,run));}catch(Exception ignored){}});try{DatagramSocket u=new DatagramSocket(null);u.setReuseAddress(true);u.setBroadcast(true);u.bind(new InetSocketAddress(DISCOVERY));udp=u;WifiManager wifi=(WifiManager)getContext().getApplicationContext().getSystemService(Context.WIFI_SERVICE);if(wifi!=null){discoveryLock=wifi.createMulticastLock(ALIAS);discoveryLock.setReferenceCounted(false);discoveryLock.acquire();}servers.execute(()->discoveryLoop(u,run));}catch(Exception ignored){udp=null;}if(cfg.has("seed"))remember(cfg.getJSONObject("seed"));}
    private JSONObject request(JSONObject peer,String action,String hash,int run)throws Exception{check(run);String address=peer.getString("ip");if(!privateIp(address))throw new IOException("Sync is local-network only");String nonce=random(16),body=seal(new JSONObject().put("nonce",nonce).put("at",System.currentTimeMillis()).put("action",action).put("hash",hash).put("device",cfg.getString("device")).put("port",port).toString(),cfg.getString("key"),"request");HttpURLConnection c=(HttpURLConnection)new URL("http",address,peer.getInt("port"),"/sync").openConnection();outgoing=c;try{c.setInstanceFollowRedirects(false);c.setConnectTimeout(2500);c.setReadTimeout(12000);c.setUseCaches(false);c.setRequestMethod("POST");c.setRequestProperty("Content-Type","text/plain");c.setDoOutput(true);byte[] packet=bytes(body);c.setFixedLengthStreamingMode(packet.length);try(OutputStream out=c.getOutputStream()){out.write(packet);}if(c.getResponseCode()!=200)throw new IOException("Peer is locked, busy or offline. Retrying automatically.");JSONObject reply=new JSONObject(unseal(new String(read(c.getInputStream(),MAX),StandardCharsets.UTF_8),cfg.getString("key"),"response"));check(run);if(!nonce.equals(reply.optString("nonce")))throw new IOException("Invalid sync response");return reply.getJSONObject("result");}finally{c.disconnect();if(outgoing==c)outgoing=null;}}
    private JSONObject execute(String method,JSONObject args,int run)throws Exception{
        if(method.equals("status")){loadConfig();return info();}
        if(method.equals("configure")){
            if(args.optString("action").equals("leave")){if(!prefs().edit().clear().commit())throw new IOException("Could not leave group");cfg=null;return info();}
            JSONObject next;String namespace=args.optString("namespace","library1");
            if(args.optString("action").equals("create"))next=new JSONObject().put("key",random(32)).put("device",UUID.randomUUID().toString()).put("namespace",namespace);
            else if(args.optString("action").equals("join")){String code=args.optString("code").trim();if(!code.startsWith("RCVSYNC1."))throw new IOException("Invalid pairing code");JSONObject invite=new JSONObject(new String(Base64.decode(code.substring(9),Base64.URL_SAFE|Base64.NO_WRAP),StandardCharsets.UTF_8));long now=System.currentTimeMillis();if(!invite.optString("key").matches("[a-f0-9]{64}")||!invite.optString("primary").matches("[a-f0-9-]{36}")||!namespace.equals(invite.optString("namespace"))||invite.optLong("expires")<now||invite.optLong("expires")>now+15*60000||!privateIp(invite.optString("ip"))||invite.optInt("port")<1024||invite.optInt("port")>65535)throw new IOException("Pairing code is expired or belongs to a different edition");next=new JSONObject().put("key",invite.getString("key")).put("primary",invite.getString("primary")).put("device",UUID.randomUUID().toString()).put("namespace",namespace).put("seed",new JSONObject().put("id",invite.getString("device")).put("ip",invite.getString("ip")).put("port",invite.getInt("port")));}
            else throw new IOException("Unknown setup action");
            String label=args.optString("label").trim();if(label.isEmpty())label=android.os.Build.MODEL;next.put("label",label.substring(0,Math.min(80,label.length())));if(!next.has("primary"))next.put("primary",next.getString("device"));if(head().exists()&&!head().delete())throw new IOException("Could not reset sync staging");save(next);resume(run);return info();
        }
        resume(run);check(run);
        if(method.equals("invite")){JSONObject invite=new JSONObject();for(String k:new String[]{"key","primary","device","namespace"})invite.put(k,cfg.get(k));invite.put("ip",ip).put("port",port).put("expires",System.currentTimeMillis()+10*60000);return new JSONObject().put("code","RCVSYNC1."+Base64.encodeToString(bytes(invite.toString()),Base64.URL_SAFE|Base64.NO_WRAP|Base64.NO_PADDING));}
        if(method.equals("discover")){if(cfg.has("seed")&&!peers.containsKey(cfg.getJSONObject("seed").optString("id")))remember(cfg.getJSONObject("seed"));if(udp!=null){byte[] message=bytes(signedPacket("RCVSYNC1?",random(8)));Set<String> targets=new HashSet<>();targets.add("255.255.255.255");Enumeration<NetworkInterface> nets=NetworkInterface.getNetworkInterfaces();while(nets.hasMoreElements())for(InterfaceAddress a:nets.nextElement().getInterfaceAddresses())if(a.getBroadcast()!=null)targets.add(a.getBroadcast().getHostAddress());for(String target:targets)try{udp.send(new DatagramPacket(message,message.length,InetAddress.getByName(target),DISCOVERY));}catch(Exception ignored){}}Thread.sleep(750);check(run);JSONArray list=new JSONArray();for(JSONObject p:peers.values())if(System.currentTimeMillis()-p.optLong("seen")<5*60000)list.put(p);return new JSONObject().put("peers",list);}
        if(method.equals("put")){String text=args.optString("text");if(bytes(text).length>CHUNK)throw new IOException("Sync chunk too large");String hash=digest(text);File f=chunk(hash);boolean valid=false;if(f.exists())try{unseal(file(f),cfg.getString("key"),"blob:"+hash);valid=true;}catch(Exception ignored){}if(!valid)atomic(f,seal(text,cfg.getString("key"),"blob:"+hash));return new JSONObject().put("hash",hash);}
        if(method.equals("beginPublish")){retained.clear();return new JSONObject();}
        if(method.equals("retain")){JSONArray hashes=args.getJSONArray("hashes");if(hashes.length()>1024)throw new IOException("Too many chunk references");for(int i=0;i<hashes.length();i++){String h=hashes.getString(i);chunk(h);retained.add(h);}return new JSONObject();}
        if(method.equals("publish")){String value=args.getJSONObject("head").toString();if(bytes(value).length>MAX/2)throw new IOException("Invalid index header");for(String h:retained)if(!chunk(h).exists())throw new IOException("A referenced chunk is missing");atomic(head(),seal(value,cfg.getString("key"),"head"));File[] files=new File(directory(),"chunks").listFiles();if(files!=null)for(File f:files)if(f.getName().matches("[a-f0-9]{64}")&&!retained.contains(f.getName())&&System.currentTimeMillis()-f.lastModified()>86400000)f.delete();return new JSONObject();}
        if(method.equals("index")||method.equals("chunk")){if(method.equals("chunk")){String hash=args.getString("hash");File f=chunk(hash);if(f.exists())try{String text=unseal(file(f),cfg.getString("key"),"blob:"+hash);if(digest(text).equals(hash)&&bytes(text).length<=CHUNK)return new JSONObject().put("text",text);}catch(Exception ignored){}}JSONObject peer=peers.get(args.optString("peer"));if(peer==null)throw new IOException("Waiting for paired device on this network");JSONObject result=request(peer,method,args.optString("hash"),run);if(method.equals("index")){if(!peer.getString("id").equals(result.optString("device")))throw new IOException("Peer identity changed");JSONArray list=result.optJSONArray("peers");if(list!=null)for(int i=0;i<Math.min(32,list.length());i++)remember(list.getJSONObject(i));return result;}String hash=args.getString("hash"),packet=result.getString("packet"),text=unseal(packet,cfg.getString("key"),"blob:"+hash);if(!digest(text).equals(hash)||bytes(text).length>CHUNK)throw new IOException("Sync chunk checksum failed");atomic(chunk(hash),packet);return new JSONObject().put("text",text);}
        throw new IOException("Unknown sync operation");
    }
    @PluginMethod public void dispatch(PluginCall call){String method=call.getString("method","");if(method.equals("pause")){pauseWork();call.resolve();return;}if(method.equals("configure"))pauseWork();final int run=epoch;if(getActivity()==null){call.reject("Open Rolecraft to sync");return;}getActivity().runOnUiThread(()->{if(getBridge()==null||getBridge().getWebView()==null||run!=epoch){call.reject("Sync paused");return;}getBridge().getWebView().evaluateJavascript("Boolean(document.querySelector('.rcv[data-rcv-state=\"ready\"]'))",ready->{if(!"true".equals(ready)||run!=epoch){call.reject("Unlock the vault to sync");return;}lease=System.currentTimeMillis()+20000;worker.execute(()->{try{if(run!=epoch)throw new IOException("Sync paused");JSONObject result=execute(method,call.getObject("args",new JSObject()),run);if(run!=epoch)throw new IOException("Sync paused");call.resolve(JSObject.fromJSONObject(result));}catch(Exception e){if(method.equals("discover")&&server!=null)pauseWork();call.reject(e.getMessage()==null?"Sync could not complete":e.getMessage());}});});});}
}
